import{a as S,S as B,i as y}from"./assets/vendor-C1DvvBV_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const P="16575326-2aaf0836bf0e7c9f61deb233c",p=15;async function g(e,o=1){const a=await S("https://pixabay.com/api/",{params:{key:P,q:e,page:o,per_page:p,image_type:"photo",orientation:"horizontal",safesearch:!0}});return console.log(a.data),a.data}const v=new B(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),i={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")};function q(){i.gallery.innerHTML=""}function h(e){const o=e.map(({largeImageURL:a,webformatURL:c,tags:t,likes:r,views:n,comments:b,downloads:M})=>`<li class="gallery-item">
            <a class="gallery-item-link" href="${a}"><img src="${c}" alt="${t}"></a>
            <ul class="gallery-img-info">
              <li class="gallery-info-item">Likes <span>${r}</span></li>
              <li class="gallery-info-item">Views <span>${n}</span></li>
              <li class="gallery-info-item">Comments <span>${b}</span></li>
              <li class="gallery-info-item">Downloads <span>${M}</span></li>
            </ul>
      </li>`).join("");i.gallery.insertAdjacentHTML("beforeend",o),v.refresh()}function u(){i.loader.classList.add("show")}function L(){i.loader.classList.remove("show")}function $(){i.loadMoreBtn.classList.add("show")}function m(){i.loadMoreBtn.classList.remove("show")}let l=1,s="",d=0;i.form.addEventListener("submit",E);async function E(e){if(e.preventDefault(),s=e.currentTarget.elements["search-text"].value.trim(),!!s){l=1,d=0,q(),m(),u();try{let{hits:o,totalHits:a}=await g(s,l);a>0?(d=Math.ceil(a/p),h(o),u()):f(`Sorry, there are no images matching your ${s}. Please try again!`)}catch(o){f(o)}L(),w()}}i.loadMoreBtn.addEventListener("click",O);async function O(){l++,m(),u();try{let{hits:e}=await g(s,l);h(e),I()}catch(e){f(e)}L(),w()}function f(e){y.error({position:"topRight",message:e})}function x(e){y.info({position:"topRight",message:e})}function w(){l>=d?(m(),x("We're sorry, but you've reached the end of search results.")):$()}function I(){const e=document.querySelector(".gallery-item"),{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
