import{a as f,S as u,i as m}from"./assets/vendor-B4VkUtbg.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d="16575326-2aaf0836bf0e7c9f61deb233c";function p(o){return f("https://pixabay.com/api/",{params:{key:d,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(({data:t})=>t)}const y=new u(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),l={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),loader:document.querySelector(".loader")};function g(){l.gallery.innerHTML=""}function h(o){console.log("create : ",o),l.gallery.innerHTML=o.map(({largeImageURL:t,webformatURL:i,tags:n,likes:e,views:r,comments:a,downloads:c})=>`<li class="gallery-item">
            <a class="gallery-item-link" href="${t}"><img src="${i}" alt="${n}"></a>
            <ul class="gallery-img-info">
              <li class="gallery-info-item">Likes <span>${e}</span></li>
              <li class="gallery-info-item">Views <span>${r}</span></li>
              <li class="gallery-info-item">Comments <span>${a}</span></li>
              <li class="gallery-info-item">Downloads <span>${c}</span></li>
            </ul>
      </li>`).join(""),y.refresh()}function L(){l.loader.classList.add("show")}function b(){l.loader.classList.remove("show")}l.form.addEventListener("submit",w);function w(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();t&&(g(),L(),p(t).then(({hits:i})=>{i.length>0?h(i):s(`Sorry, there are no images matching your ${t}. Please try again!`)}).catch(i=>s(i)).finally(()=>b()))}function s(o){m.error({position:"topRight",message:o})}
//# sourceMappingURL=index.js.map
